name: "Moole Security"
description: "Reads top-level build file, base64-encodes, sends JSON to your scanner"
author: "you"
branding:
  icon: upload-cloud
  color: blue

inputs:
  api_token:
    description: "API token to include in request body (NOT a header)"
    required: false
  pat:
    description: "Personal access token to include in request body"
    required: false

  project:
    description: "Project identifier (sent as projectId)"
    required: true
  environment:
    description: "Environment identifier (sent as envId)"
    required: true

  root_dir:
    description: "Directory to scan (default repo root)"
    required: false
    default: "."
  additional_fields:
    description: "Optional JSON merged into payload.metadata"
    required: false
  fail_on_missing_files:
    description: "Fail if no top-level build file is found"
    required: false
    default: "true"
  max_payload_mb:
    description: "Fail if JSON payload exceeds this many MB"
    required: false
    default: "5"

outputs:
  files_found:
    description: "1 if a build file was included, else 0"
  response_code:
    description: "HTTP status code"
  response_body:
    description: "Truncated response body"
  packages_count:
    description: "Unique dependency GAV count parsed from response"
  vulnerabilities_count:
    description: "Unique CVE count parsed from response"
  severity_counts:
    description: "JSON object with CRITICAL/HIGH/MEDIUM/LOW counts"
  report_url:
    description: "Report URL from API, if present"

runs:
  using: "node20"
  main: "dist/index.js"